### ISSUE TITLE
关于解码器

### ISSUE THREAD

**Issue by valar000** [sjcfr/CWVAE#1]
1. 图上画的是 双向gru 论文里面没有提到，请问是以图为准吗？
2. ![image](https://user-images.githubusercontent.com/12813872/68081901-4af63900-fe50-11e9-87a9-faea3132a9ef.png) 这一部分的 hidden state 是什么

**Comment by sjcfr** [comment]
1. 是单向的……
2. []里面zj-1是笔误，应为zc'...下文里面也说through concatenating z, zc', Eyj and sj-1

**Comment by valar000** [comment]
请问解码器也是双向gru吗？
Neural Decoder  这一章并没有说明，而图上画读是 bi-gru

**Comment by sjcfr** [comment]
是单向的……

**Comment by valar000** [comment]
![image](https://user-images.githubusercontent.com/12813872/68173559-48155880-ffb6-11e9-9c68-c509b02eb765.png)
这一部分 怎么用到了 hy 和图上也不一致
